parameters:
    # Adds a fallback VARNISH_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(VARNISH_URL): ''

api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/App/Entity'
            - '%kernel.project_dir%/src/Aaas/Entity'
    title: API as a Service - API
    description: This is the API for API as a Service.
    version: 1.3.0
    enable_re_doc: false
    path_segment_name_generator: 'App\Operation\CamelCasePathSegmentNameGenerator'
    collection:
        pagination:
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage