dist: precise
language: php
php: [ 7.2, 7.3, 7.4 ]
sudo: false

branches:
    only:
        - release
        - develop

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_install:
    - sudo mysql -u root -e 'CREATE DATABASE app_test;'
    - sudo mysql -u root -e "CREATE USER 'app'@'localhost' IDENTIFIED BY 'app';"
    - sudo mysql -u root -e "GRANT ALL ON app_test.* TO 'app'@'localhost';"

install:
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --no-interaction
    - php bin/console doctrine:migrations:migrate --no-interaction --env=test
    - php bin/console doctrine:fixtures:load --no-interaction --env=test
    - openssl genrsa -out config/jwt/private-test.pem -aes256 -passout pass:app! 4096
    - openssl rsa -pubout -in config/jwt/private-test.pem -out config/jwt/public-test.pem -passin pass:app!

script:
    - $TRAVIS_BUILD_DIR/bin/phpunit -c config/ci/phpunit.xml.dist --no-coverage

addons:
    mariadb: '10.5'
    hosts:
        - mariadb_test

cache:
    directories:
        - $HOME/.composer
        - ./docker
