language: php
php: [ 7.3 ]
sudo: false

branches:

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

install:
    - travis_retry composer install --no-interaction --prefer-dist --optimize-autoloader
before_script:
    - travis_retry composer global require phpunit/phpunit ^6 # cannot use phpunit.phar or require-dev, because this package is a phpunit dep
script:
    - $HOME/.composer/vendor/bin/phpunit --no-coverage

jobs:
    include:

        - stage: analysis
          php: 7.3
          name: "Phpunit code coverage and analysis"
          script:
              - $HOME/.composer/vendor/bin/phpunit --coverage-html ./build/coverage
          after_success:
              - $TRAVIS_BUILD_DIR/vendor/bin/phpcs --report=xml --report-file=./build/phpcs.xml
              - $TRAVIS_BUILD_DIR/vendor/bin/phpmd src/ html phpmd.xml.dist --reportfile ./build/phpmd.html
              - $TRAVIS_BUILD_DIR/vendor/vendor/bin/pdepend --summary-xml=./build/php-pdepend.xml --jdepend-chart=./build/php-jdepend.svg --overview-pyramid=./build/php-pyramid.svg --ignore=src/Migrations/ ./src

cache:
    directories:
        - $HOME/.composer
        - ./docker