language: php
php: [ 7.1, 7.2, 7.3, nightly ]
sudo: false

branches:

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

install:
    - travis_retry composer install --no-interaction --prefer-dist --optimize-autoloader
script:
    - $TRAVIS_BUILD_DIR/bin/phpunit --no-coverage

jobs:
    include:

        - stage: Test
          php: 7.3
          name: "PHPUnit"
          script:
              - $HOME/.composer/vendor/bin/phpunit --no-coverage

cache:
    directories:
        - $HOME/.composer
        - ./docker