language: php
php: [ 7.3 ]
sudo: false

branches:

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

install:
    - travis_retry composer install --no-interaction --prefer-dist --optimize-autoloader
before_script:
    - travis_retry composer global require phpunit/phpunit ^6 # cannot use phpunit.phar or require-dev, because this package is a phpunit dep
script:
    - $HOME/.composer/vendor/bin/phpunit --no-coverage

jobs:
    include:

        - stage: test
          php: 7.3
          name: "php 7.1 Smoke test"
          before_script:
              - travis_retry sudo apt install graphviz
          script:
              - ./bin/phpdoc run

        - stage: analysis
          php: 7.3
          name: "Phpunit code coverage"
          script:
              - $HOME/.composer/vendor/bin/phpunit
          after_script:
              - travis_retry wget --no-verbose https://phar.io/releases/phive.phar
              - travis_retry php phive.phar --no-progress install --trust-gpg-keys E82B2FB314E9906E php-coveralls/php-coveralls && ./tools/php-coveralls --verbose
              - travis_retry wget --no-verbose https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

cache:
    directories:
        - $HOME/.composer
        - $HOME/.phive
        - ./docker