language: php
php: [ 7.2, 7.3 ]
sudo: false

branches:

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

install:
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --no-interaction
script:
    - $TRAVIS_BUILD_DIR/bin/phpunit --no-coverage

cache:
    directories:
        - $HOME/.composer
        - ./docker