api_platform:
    enable_docs: true
    enable_swagger_ui: true
    enable_re_doc: true
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header