parameters:
    env(MERCURE_PUBLISH_URL): ''
    env(MERCURE_JWT_SECRET): ''
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/App/*'
        exclude: '../src/App/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Aaas\:
        resource: '../src/Aaas/*'
        exclude: '../src/Aaas/{Entity}'

    App\Action\:
        resource: '../src/App/Action/'
        tags: ['controller.service_arguments']

    Symfony\Bundle\MakerBundle\Generator: '@maker.generator'