parameters:
    env(MERCURE_PUBLISH_URL): ''
    env(MERCURE_JWT_SECRET): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'