parameters:
    env(MERCURE_PUBLISH_URL): ''
    env(MERCURE_JWT_SECRET): ''
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action/'
        tags: ['controller.service_arguments']

    Symfony\Bundle\MakerBundle\Generator: '@maker.generator'